name: Build Server

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo rm -f /etc/apt/sources.list.d/google-chrome.list
        sudo apt-get update -y
        sudo apt-get install -y libboost-all-dev cmake g++

    - name: Configure CMake
      run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: cmake --build build --config Release

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: join_server_executable
        path: build/join_server